//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 03:02:26 PM MSK 
//


package by.teachmeskills.soap.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faculty.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="faculty"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Mechanical engineering faculty"/&gt;
 *     &lt;enumeration value="Faculty of Energy"/&gt;
 *     &lt;enumeration value="Architecture faculty"/&gt;
 *     &lt;enumeration value="Building faculty"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "faculty")
@XmlEnum
public enum Faculty {

    @XmlEnumValue("Mechanical engineering faculty")
    MECHANICAL_ENGINEERING_FACULTY("Mechanical engineering faculty"),
    @XmlEnumValue("Faculty of Energy")
    FACULTY_OF_ENERGY("Faculty of Energy"),
    @XmlEnumValue("Architecture faculty")
    ARCHITECTURE_FACULTY("Architecture faculty"),
    @XmlEnumValue("Building faculty")
    BUILDING_FACULTY("Building faculty");
    private final String value;

    Faculty(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Faculty fromValue(String v) {
        for (Faculty c : Faculty.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
