//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 03:02:26 PM MSK 
//


package by.teachmeskills.soap.model;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for student complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="student"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sex" type="{http://www.baeldung.com/springsoap/gen}sex"/&gt;
 *         &lt;element name="faculty" type="{http://www.baeldung.com/springsoap/gen}faculty"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "student", propOrder = {
        "name",
        "lastname",
        "age",
        "sex",
        "faculty"
})
public class Student {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String lastname;
    protected int age;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Sex sex;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Faculty faculty;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastname(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the age property.
     */
    public int getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     */
    public void setAge(int value) {
        this.age = value;
    }

    /**
     * Gets the value of the sex property.
     *
     * @return possible object is
     * {@link Sex }
     */
    public Sex getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     *
     * @param value allowed object is
     *              {@link Sex }
     */
    public void setSex(Sex value) {
        this.sex = value;
    }

    /**
     * Gets the value of the faculty property.
     *
     * @return possible object is
     * {@link Faculty }
     */
    public Faculty getFaculty() {
        return faculty;
    }

    /**
     * Sets the value of the faculty property.
     *
     * @param value allowed object is
     *              {@link Faculty }
     */
    public void setFaculty(Faculty value) {
        this.faculty = value;
    }

}
